#!/bin/bash


> report.log #file cleaner

declare -a arr

counter=0

function arr_push()
{
  declare -a fill=(1 2 3 4 5 6 7 9 10)
  arr+=(${fill[@]})
}

while true; do
  arr_push
  counter+=1
  if [[ "$counter" == 100000 ]]; then
    counter=0
    echo "$#{array[@]}" >> report.log 
  fi
done
